package com.aws.dynamo.db.dto;

import java.util.List;
import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "movie")
public class Movie {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	//@DynamoDBGeneratedUuid( DynamoDBAutoGenerateStrategy.CREATE )
	@DynamoDBAttribute(attributeName = "filmid")
	private String filmid;
	@DynamoDBAttribute(attributeName = "Actors")
	private List<String> actors;
	@DynamoDBAttribute(attributeName = "rated")
	private String rated;
	@DynamoDBAttribute(attributeName = "title")
	private String title;
	@DynamoDBAttribute(attributeName = "year")
	private Integer year;

	public String getFilmid() {
		return filmid;
	}

	public void setFilmid(String filmid) {
		this.filmid = filmid;
	}

	public List<String> getActors() {
		return actors;
	}

	public void setActors(List<String> actors) {
		this.actors = actors;
	}

	public String getRated() {
		return rated;
	}

	public void setRated(String rated) {
		this.rated = rated;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getYear() {
		return year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Override
	public String toString() {
		return "Movie [filmid=" + filmid + ", actors=" + actors + ", rated=" + rated + ", title=" + title + ", year="
				+ year + "]";
	}

}
